### ISSUE TITLE
go.mod: no matching versions for query "v1.2"

### ISSUE THREAD

**Issue by d-schmidt** [anaskhan96/soup#50]
It seems go mod/get is unable to understand shorter version strings

I forked your repo and changed it to 1.2.1 and go get did work again.
Currently I'm only able to get v1.1.1

Could you release a new version with 3 digits?

**Comment by d-schmidt** [comment]
confirmed here https://github.com/golang/go/issues/37529#issuecomment-592301127

**Comment by KateGo520** [comment]
I found that this project already [supports Go modules](https://github.com/anaskhan96/soup/blob/master/go.mod). But sadly, the [tags](https://github.com/anaskhan96/soup/tags) doesn't follow [Semantic Versioning](https://semver.org), which means that all tags of this project will be ignored by Go modules and replaced by pseudo-versions, go get acts weirdly when tags are not in that form. It would be great to have the tagged release be named in the format vX.X.X format so that go mod can read it. 
So, I propose this project to follow Semantic Versioning in future versions. For example, `v1.0.1`, `v2.0.0`, `v3.1.0-alpha`, `v3.1.0-beta.2`etc.

**Comment by anaskhan96** [comment]
Done - [1.2.1](https://github.com/anaskhan96/soup/releases/tag/v1.2.1)

Sorry for the delay :/
